name: 'Get the Heroku Application Name'
description: 'Get the Heroku Application Name'
inputs:
  environment:
    description: 'The target deployment environment '
    required: true
outputs:
  heroku_application_name:
    description: 'The name of the application in Heroku for the given environment'
runs:
  using: 'node16'
  main: 'index.js'
