name: 'Create the release tag'
description: 'Creates a unique tag for this commit in GitHub'
inputs:
  github-token:
    description: 'The token to use for interacting with GitHub '
    required: true
outputs:
  release_tag:
    description: 'The tag that was created'
runs:
  using: 'node16'
  main: 'dist/index.js'
