name: 'Create tag for commit'
description: 'Creates a unique tag for this commit in GitHub'
inputs:
  github-token:
    description: 'The token to use for interacting with GitHub '
    required: true
  include-build-metadata:
    description: 'Whether to include build metadata in the generated tag (e.g. <build_number>-<short_sha>)'
    required: false
    default: 'false'
outputs:
  tag_name:
    description: 'The name of the tag that was created'
runs:
  using: 'node16'
  main: 'dist/index.js'
