# Performs auto deployments to dev and qa

on:
  workflow_call:
    inputs:
      dev_application_name:
        required: true
        type: string
      qa_application_name:
        required: true
        type: string

jobs:
  deploy_to_heroku:
    runs-on: ubuntu-latest

    env:
      AUTO_DEPLOY_TO_DEV: ${{ secrets.AUTO_DEPLOY_TO_DEV }}
      AUTO_DEPLOY_TO_QA: ${{ secrets.AUTO_DEPLOY_TO_QA }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: YQ exists
        run: yq --help

      - name: Deploy to Dev
        # uses: akhileshns/heroku-deploy@v3.12.12
        if: ${{ env.AUTO_DEPLOY_TO_DEV == 'true' }}
        run: echo "Deploying to ${{ inputs.dev_application_name }}"
        # with:
          # heroku_app_name: ${{ inputs.dev_application_name }}
          # heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          # heroku_email: ${{ secrets.HEROKU_EMAIL }}

      - name: Deploy to QA
        # uses: akhileshns/heroku-deploy@v3.12.12
        if: ${{ env.AUTO_DEPLOY_TO_QA == 'true' }}
        run: echo "Deploying to ${{ inputs.qa_application_name }}"
        # with:
          # heroku_app_name: ${{ inputs.qa_application_name }} 
          # heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          # heroku_email: ${{ secrets.HEROKU_EMAIL }}
