# Performs auto deployments to dev and qa

on:
  workflow_call:
    inputs:
      dev_application_name:
        required: true
        type: string
      qa_application_name:
        required: true
        type: string

jobs:
  deploy_to_heroku:
    runs-on: ubuntu-latest

    env:
      AUTO_DEPLOY_TO_DEV: ${{ secrets.AUTO_DEPLOY_TO_DEV }}
      AUTO_DEPLOY_TO_QA: ${{ secrets.AUTO_DEPLOY_TO_QA }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Create a Release Tag
        id: create-commit-tag
        uses: romack/shared-workflows/.github/actions/create-commit-tag@main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Deploy to Dev
        run: echo "Deploying to ${{ inputs.dev_application_name }}"