on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string

jobs:
  deploy_to_heroku:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Dump GitHub context
        id: github_context_step
        run: echo '${{ toJSON(github) }}'
      - name: Dump job context
        run: echo '${{ toJSON(job) }}'
      - name: Dump steps context
        run: echo '${{ toJSON(steps) }}'
      - name: Dump runner context
        run: echo '${{ toJSON(runner) }}'
      - name: Dump strategy context
        run: echo '${{ toJSON(strategy) }}'
      - name: Dump matrix context
        run: echo '${{ toJSON(matrix) }}'

      - name: Create Non Prod Tag
        id: create-non-prod-tag
        uses: romack/shared-workflows/.github/actions/create-commit-tag@main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          include-build-metadata: true

      - name: Echo Non Prod Tag
        run: echo "Release Tag ${{ steps.create-non-prod-tag.outputs.tag_name }}"

      - name: Create Prod Tag
        id: create-prod-tag
        uses: romack/shared-workflows/.github/actions/create-commit-tag@main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Echo Prod Tag
        run: echo "Release Tag ${{ steps.create-prod-tag.outputs.tag_name }}"