on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string

jobs:
  deploy_to_heroku:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Include Metadata == true
        uses: romack/shared-workflows/.github/actions/create-commit-tag@main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          include-build-metadata: true

      - name: Include Metadata == 'true'
        uses: romack/shared-workflows/.github/actions/create-commit-tag@main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          include-build-metadata: 'true'

      - name: Include Metadata == false
        uses: romack/shared-workflows/.github/actions/create-commit-tag@main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          include-build-metadata: false

      - name: Include Metadata == 'false'
        uses: romack/shared-workflows/.github/actions/create-commit-tag@main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          include-build-metadata: 'false'

      - name: Include Metadata undefined
        uses: romack/shared-workflows/.github/actions/create-commit-tag@main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}