on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string

jobs:
  deploy_to_heroku:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Get Heroku Application Name
        run: |
          applicationName=$(echo ${{ github.repository }} | sed "s|${{ github.repository_owner }}/||g")
          defaultHerokuApplicationName="invh-${applicationName}-${{ inputs.environment }}"
          herokuApplicationNameOverride=$(cat .repo-metadata.yaml| yq '.deployment["heroku-application-name"]'.${{ inputs.environment }} | sed s/\"//g 2>/dev/null)
          echo "Default Application Name ${defaultHerokuApplicationName}"
          echo "Override Application Name ${herokuApplicationNameOverride}"

      - name: Echo Environment
        run: echo "Environment ${{ inputs.environment }}"

      - name: Echo Repository
        run: echo "Repository ${{ github.repository }}"

      - name: Echo Repository Owner
        run: echo "Reopsitory Owner ${{ github.repository_owner }}"

      - name: Echo Inherited Secret
        run: echo "Test Secret ${{ secrets.TEST_SECRET }}"

      - name: Echo Non-Existant Secret
        run: echo "Non-Existant Secret ${{ secrets.BAD_SECRET }}"
