on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string

jobs:
  deploy_to_heroku:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Get Heroku Application Name
        id: get-heroku-application-name
        uses: romack/shared-workflows/.github/actions/get-heroku-application-name@main
        with:
          environment: ${{ inputs.environment }}

      - name: Create a Release Tag
        id: create-commit-tag
        uses: romack/shared-workflows/.github/actions/create-commit-tag@main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Echo Heroku Application Name
        run: echo "Heroku Application Name ${{ steps.get-heroku-application-name.outputs.heroku_application_name }}"

      - name: Echo Release Tag
        run: echo "Release Tag ${{ steps.create-commit-tag.outputs.release_tag }}"
