on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string

jobs:
  deploy_to_heroku:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

       - name: Get Heroku App Name Action
         id: get-heroku-application-name
         uses: romack/shared-workflows/.github/actions/get-heroku-application-name@main
         with:
           environment: ${{ inputs.environment }}
