on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string

jobs:
  deploy_to_heroku:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

        # TODO: pull this out to a custom action
      - name: Get Heroku Application Name
        run: |
          applicationName=$(echo ${{ github.repository }} | sed "s|${{ github.repository_owner }}/||g")
          echo "Application Name ${applicationName}"
          herokuApplicationName=$(cat .repo-metadata.yaml | yq '.deployment."heroku-application-name"'.${{ inputs.environment }} | sed "s|\"||g" 2>/dev/null)
          echo "Heroku Application Name ${herokuApplicationName}"
          if [ -z "$herokuApplicationName" ]
          then
              echo "Heroku application name is null"
              herokuApplicationName="invh-${applicationName}-${{ inputs.environment }}"
          fi
          echo "Heroku Application Name ${herokuApplicationName}"

      - name: Get the output
        run: echo "App was ${{ steps.get-heroku-application-name.outputs.heroku_application_name }}"

      - name: Echo Environment
        run: echo "Environment ${{ inputs.environment }}"

      - name: Echo Repository
        run: echo "Repository ${{ github.repository }}"

      - name: Echo Repository Owner
        run: echo "Reopsitory Owner ${{ github.repository_owner }}"

      - name: Echo Inherited Secret
        run: echo "Test Secret ${{ secrets.TEST_SECRET }}"

      - name: Echo Non-Existant Secret
        run: echo "Non-Existant Secret ${{ secrets.BAD_SECRET }}"
