name: Deploy to Heroku

on:
  workflow_call:
    inputs:
      application_name:
        required: true
        type: string
    secrets: inherit

jobs:
  deploy_to_heroku:
    runs-on: ubuntu-latest
    steps:
      - name: Echo Application Name
        run: echo "Application Name ${{ inputs.application_name }}"
      - name: Echo Inherited Secret
        run: echo "Test Secret ${{ secrets.TEST_SECRET }}"
