on:
  workflow_call:
    inputs:
      application_name:
        required: true
        type: string

jobs:
  deploy_to_heroku:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Echo Application Name
        run: echo "Application Name ${{ inputs.application_name }}"

      - name: Echo Inherited Secret
        run: echo "Test Secret ${{ secrets.TEST_SECRET }}"

      - name: Echo Non-Existant Secret
        run: echo "Non-Existant Secret ${{ secrets.BAD_SECRET }}"
