on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string

jobs:
  deploy_to_heroku:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Create Non Prod Tag
        id: create-non-prod-tag
        uses: romack/shared-workflows/.github/actions/create-commit-tag@main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Echo Non Prod Tag
        run: echo "Release Tag ${{ steps.create-non-prod-tag.outputs.tag_name }}"

      - name: Create Prod Tag
        id: create-prod-tag
        uses: romack/shared-workflows/.github/actions/create-commit-tag@main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Echo Prod Tag
        run: echo "Release Tag ${{ steps.create-prod-tag.outputs.tag_name }}"